"use client";

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {ApolloProvider, ApolloClient, InMemoryCache} from "@apollo/client"

const client = new ApolloClient({
	uri: 'http://localhost:8080/graphql',
  cache: new InMemoryCache(),
});

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
		<ApolloProvider client={client}>
			<html lang="en">
				<body className={inter.className}>{children}</body>
			</html>
		</ApolloProvider>
  );
}
